---
- name: Add firmware to Server Profiles in OneView
  hosts: uc3_targets
  gather_facts: false

  vars:
    firmware: true

  tasks:
    - name: define ov_hardware according to inventory name
      ansible.builtin.set_fact:
        ov_hostname: "{{ inventory_hostname }}"
        ov_hardware: "{{ inventory_hostname }}.hpintelco.org"

    - name: debug server profle
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', 'server_profile_template.j2') | from_yaml }}"
      when: debug | default('false') | bool

    - name: Create a server profile
      delegate_to: localhost
      register: result
      hpe.oneview.oneview_server_profile:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        api_version: "{{ oneview_apiversion }}"
        state: present
        data:
          "{{ lookup('ansible.builtin.template', 'server_profile_template.j2') | from_yaml }}"
        params:
          force: true

    - name: debug message to reboot the server
      ansible.builtin.debug:
        msg: "Please run update_esxi or reboot the server manually to apply all firmware updates"
