---
- name: Add firmware to Server Profiles in OneView
  hosts: oneview_servers
  gather_facts: false

  tasks:

    - name: Create a server profile
      delegate_to: localhost
      register: result
      hpe.oneview.oneview_server_profile:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        api_version: "{{ oneview_apiversion }}"
        state: present
        data:
          "{{ lookup('ansible.builtin.template', 'server_profile_template.j2') | from_yaml }}"
        params:
          force: true
