---
- name: Playbook to update ESXi host
  hosts: uc3_targets
  become: false
  gather_facts: false
  serial: 1

  tasks:
    - name: Enter VSAN-Compliant Maintenance Mode for the defined host {{ ansible_host }}
      community.vmware.vmware_maintenancemode:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        esxi_hostname: "{{ ansible_host }}"
        vsan: ensureObjectAccessibility
        evacuate: true
        timeout: 3600
        state: present
      delegate_to: localhost

    - name: ESXi enable http traffic
      ansible.builtin.shell:
        "esxcli network firewall ruleset set -e true -r httpClient"

    - name: ESXi Install Update
      ansible.builtin.shell:
        "esxcli software profile update -p {{ my_esxi_package }} -d https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml"
        # If offline: "esxcli software profile update -d /vmfs/volumes/XXXXXXXXXXX/ESXi670-202102001.zip -p ESXi-6.7.0-20210204001-standard"
      register: vib

    - name: Print output of update command
      ansible.builtin.debug:
        var: vib.stdout_lines

    - name: ESXi reboot
      community.vmware.vmware_host_powerstate:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        esxi_hostname: "{{ ansible_host }}"
        timeout: 3600
        state: reboot-host
      delegate_to: localhost

    - name: ESXi wait for the reboot to complete
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 443
        delay: 360
        state: started
        timeout: 3600
      delegate_to: localhost

    - name: ESXi exit maintenance
      community.vmware.vmware_maintenancemode:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        esxi_hostname: "{{ ansible_host }}"
        vsan: ensureObjectAccessibility
        evacuate: true
        timeout: 3600
        state: absent
      delegate_to: localhost
